class_name LevelCatalog
extends RefCounted

# Authoritative campaign metadata and map source.

const AREA_01_LEVELS := [
	{
		"id": "1-0",
		"name": "Push",
		"cell": Vector2i(0, 0),
		"route": "main",
		"requires": [],
		"source": "!cell-edge-v1\n\n[cells]\n##..##\n@.A.B*\n..#.#.\n###*..\n\n[horizontal_edges]\n......\n......\n......\n\n[vertical_edges]\n.....\n.....\n.....\n.....",
	},
	{
		"id": "1-1",
		"name": "Corner",
		"cell": Vector2i(1, 0),
		"route": "main",
		"requires": ["1-0"],
		"source": "!cell-edge-v1\n\n[cells]\n##.*\n@A..\n#..#\n\n[horizontal_edges]\n....\n....\n\n[vertical_edges]\n...\n...\n...",
	},
	{
		"id": "1-2",
		"name": "Transfer",
		"cell": Vector2i(2, 0),
		"route": "main",
		"requires": ["1-1"],
		"source": "!cell-edge-v1\n\n[cells]\n#*##\n.B#*\n@.A.\n\n[horizontal_edges]\n....\n....\n\n[vertical_edges]\n...\n...\n...",
	},
	{
		"id": "1-3",
		"name": "Fetch",
		"cell": Vector2i(3, 0),
		"route": "main",
		"requires": ["1-2"],
		"source": "!cell-edge-v1\n\n[cells]\n#*#\nB..\n#..\n@A*\n\n[horizontal_edges]\n...\n...\n...\n\n[vertical_edges]\n..\n..\n..\n..",
	},
	{
		"id": "1-4",
		"name": "Divide",
		"cell": Vector2i(3, 1),
		"route": "main",
		"requires": ["1-3"],
		"source": "!cell-edge-v1\n\n[cells]\n#@A.*\nB*#C*\n\n[horizontal_edges]\n.....\n\n[vertical_edges]\n....\n....",
	},
	{
		"id": "1-5",
		"name": "Fence",
		"cell": Vector2i(2, 1),
		"route": "main",
		"requires": ["1-4"],
		"source": "!cell-edge-v1\n\n[cells]\n#A*#\n@B.*\n#C*#\n\n[horizontal_edges]\n.--.\n.--.\n\n[vertical_edges]\n...\n...\n...",
	},
	{
		"id": "1-6",
		"name": "Pull",
		"cell": Vector2i(1, 1),
		"route": "branch",
		"requires": ["1-5"],
		"source": "!cell-edge-v1\n\n[cells]\n##@\na#*\n..B\n...\n\n[horizontal_edges]\n...\n...\n...\n\n[vertical_edges]\n..\n..\n..\n..",
	},
	{
		"id": "1-7",
		"name": "Return",
		"cell": Vector2i(0, 1),
		"route": "main",
		"requires": ["1-5"],
		"source": "!cell-edge-v1\n\n[cells]\n@#.#\nA*B.\n*..#\n\n[horizontal_edges]\n....\n....\n\n[vertical_edges]\n...\n...\n|..",
	},
	{
		"id": "1-8",
		"name": "Cross",
		"cell": Vector2i(0, 2),
		"route": "branch",
		"requires": ["1-7"],
		"source": "!cell-edge-v1\n\n[cells]\n#.##\n.B@*\n#.a#\n##.#\n\n[horizontal_edges]\n....\n....\n....\n\n[vertical_edges]\n...\n...\n...\n...",
	},
	{
		"id": "1-9",
		"name": "Exchange",
		"cell": Vector2i(1, 2),
		"route": "main",
		"requires": ["1-7"],
		"source": "!cell-edge-v1\n\n[cells]\n.b#\n.@.\n*.A\n.C*\n\n[horizontal_edges]\n...\n...\n...\n\n[vertical_edges]\n..\n..\n..\n..",
	},
	{
		"id": "1-10",
		"name": "Invert",
		"cell": Vector2i(2, 2),
		"route": "main",
		"requires": ["1-9"],
		"source": "!cell-edge-v1\n\n[cells]\n#...#\n...A@\n##.*#\n\n[horizontal_edges]\n.....\n...-.\n\n[vertical_edges]\n....\n....\n....",
	},
	{
		"id": "1-11",
		"name": "Spring",
		"cell": Vector2i(3, 2),
		"route": "branch",
		"requires": ["1-10"],
		"source": "!cell-edge-v1\n\n[cells]\n.C..*\n...A*\n##@..\n*.B.#\n\n[horizontal_edges]\n-----\n...--\n.....\n\n[vertical_edges]\n....\n....\n....\n....",
	},
]


const AREA_02_LEVELS := [
	{
		"id": "2-1",
		"name": "Contact",
		"cell": Vector2i(0, 0),
		"route": "main",
		"requires": [],
		"source": "!cell-edge-v1\n\n[cells]\n#####\n@A*B*\n#####\n\n[horizontal_edges]\n.....\n.....\n\n[vertical_edges]\n....\n....\n....",
	},
	{
		"id": "2-2",
		"name": "Caterpillar",
		"cell": Vector2i(1, 0),
		"route": "branch",
		"requires": ["2-1"],
		"source": "!cell-edge-v1\n\n[cells]\n#######\n**.B.A@\n#######\n\n[horizontal_edges]\n.......\n.......\n\n[vertical_edges]\n......\n......\n......",
	},
	{
		"id": "2-3",
		"name": "Align",
		"cell": Vector2i(2, 0),
		"route": "main",
		"requires": ["2-1"],
		"source": "!cell-edge-v1\n\n[cells]\n*##\nB##\n...\n#A.\n#@#\n\n[horizontal_edges]\n...\n...\n...\n...\n\n[vertical_edges]\n..\n..\n..\n..\n..",
	},
	{
		"id": "2-4",
		"name": "Agent",
		"cell": Vector2i(3, 0),
		"route": "branch",
		"requires": ["2-3"],
		"source": "!cell-edge-v1\n\n[cells]\n####.\n##*B.\n##.#*\n@A...\n...##\n\n[horizontal_edges]\n.....\n.....\n.....\n.....\n\n[vertical_edges]\n....\n....\n....\n....\n....",
	},
	{
		"id": "2-5",
		"name": "Collision",
		"cell": Vector2i(3, 1),
		"route": "main",
		"requires": ["2-3"],
		"source": "!cell-edge-v1\n\n[cells]\n@A*#\n..##\n#BC#\n#*d*\n\n[horizontal_edges]\n....\n....\n....\n\n[vertical_edges]\n...\n...\n...\n...",
	},
	{
		"id": "2-6",
		"name": "Rebound",
		"cell": Vector2i(2, 1),
		"route": "branch",
		"requires": ["2-5"],
		"source": "!cell-edge-v1\n\n[cells]\n#@##\n.A##\n*.C*\n#B..\n#*..\n\n[horizontal_edges]\n....\n....\n....\n....\n\n[vertical_edges]\n...\n...\n...\n...\n...",
	},
	{
		"id": "2-7",
		"name": "Handoff",
		"cell": Vector2i(1, 1),
		"route": "main",
		"requires": ["2-5"],
		"source": "!cell-edge-v1\n\n[cells]\n*###\nA*.*\n@CD#\n.B*#\n\n[horizontal_edges]\n....\n....\n....\n\n[vertical_edges]\n...\n|..\n|..\n...",
	},
	{
		"id": "2-8",
		"name": "Array",
		"cell": Vector2i(0, 1),
		"route": "branch",
		"requires": ["2-7"],
		"source": "!cell-edge-v1\n\n[cells]\n#@##\n.A##\n...#\n#BC.\n#***\n\n[horizontal_edges]\n....\n....\n....\n....\n\n[vertical_edges]\n...\n...\n...\n.|.\n...",
	},
	{
		"id": "2-9",
		"name": "Transmit",
		"cell": Vector2i(0, 2),
		"route": "main",
		"requires": ["2-7"],
		"source": "!cell-edge-v1\n\n[cells]\n#ABC.*\n.@.###\n#.D..*\n\n[horizontal_edges]\n.--...\n......\n\n[vertical_edges]\n.....\n.....\n.....",
	},
	{
		"id": "2-10",
		"name": "Intermediate",
		"cell": Vector2i(1, 2),
		"route": "branch",
		"requires": ["2-9"],
		"source": "!cell-edge-v1\n\n[cells]\n...###\n....C#\n.A#BD*\n.@##*#\n\n[horizontal_edges]\n......\n...-..\n......\n\n[vertical_edges]\n.....\n...|.\n.....\n.....",
	},
	{
		"id": "2-11",
		"name": "Perpendicular",
		"cell": Vector2i(2, 2),
		"route": "main",
		"requires": ["2-9"],
		"source": "!cell-edge-v1\n\n[cells]\n##@#\n..A#\n...#\n.B*#\n##.*\n\n[horizontal_edges]\n....\n....\n....\n....\n\n[vertical_edges]\n...\n...\n...\n...\n...",
	},
	{
		"id": "2-12",
		"name": "Follow",
		"cell": Vector2i(3, 2),
		"route": "branch",
		"requires": ["2-11"],
		"source": "!cell-edge-v1\n\n[cells]\n.###\nB#**\n@.D#\nAC.#\n.###\n\n[horizontal_edges]\n....\n....\n.-..\n....\n\n[vertical_edges]\n...\n...\n.|.\n...\n...",
	},
]


const AREA_03_LEVELS := [
	{
		"id": "3-1",
		"name": "Unlock",
		"cell": Vector2i(0, 0),
		"route": "main",
		"requires": [],
		"source": "!cell-edge-v1\n\n[cells]\n.C*\n.B.\n#.#\n@A*\n\n[horizontal_edges]\n...\n...\n...\n\n[vertical_edges]\n..\n..\n..\n..",
	},
	{
		"id": "3-2",
		"name": "Launcher",
		"cell": Vector2i(1, 0),
		"route": "main",
		"requires": ["3-1"],
		"source": "!cell-edge-v1\n\n[cells]\n.A*##\n...C*\n.@.D*\nB...#\n\n[horizontal_edges]\n.....\n.....\n.---.\n\n[vertical_edges]\n....\n..|.\n..|.\n....",
	},
	{
		"id": "3-3",
		"name": "Recover",
		"cell": Vector2i(2, 0),
		"route": "main",
		"requires": ["3-2"],
		"source": "!cell-edge-v1\n\n[cells]\n.c.b\n...@\n..A*\n\n[horizontal_edges]\n-.-.\n....\n\n[vertical_edges]\n...\n.|.\n...",
	},
	{
		"id": "3-4",
		"name": "Vault",
		"cell": Vector2i(2, 1),
		"route": "main",
		"requires": ["3-3"],
		"source": "!cell-edge-v1\n\n[cells]\n....\nABCD\n*+**\n\n[horizontal_edges]\n....\n....\n\n[vertical_edges]\n...\n...\n...",
	},
	{
		"id": "3-5",
		"name": "Interlock",
		"cell": Vector2i(1, 1),
		"route": "main",
		"requires": ["3-4"],
		"source": "!cell-edge-v1\n\n[cells]\n#...\nCB*A\n*#@.\n##..\n\n[horizontal_edges]\n....\n....\n....\n\n[vertical_edges]\n.|.\n...\n...\n...",
	},
	{
		"id": "3-6",
		"name": "Delay",
		"cell": Vector2i(0, 1),
		"route": "main",
		"requires": ["3-5"],
		"source": "!cell-edge-v1\n\n[cells]\n#a..\n@B..\n#*..\n\n[horizontal_edges]\n..--\n....\n\n[vertical_edges]\n...\n...\n...",
	},
	{
		"id": "3-7",
		"name": "Cycle",
		"cell": Vector2i(0, 2),
		"route": "main",
		"requires": ["3-6"],
		"source": "!cell-edge-v1\n\n[cells]\n*@B\n.A.\n#*.\n#..\n\n[horizontal_edges]\n...\n...\n...\n\n[vertical_edges]\n..\n..\n..\n..",
	},
	{
		"id": "3-8",
		"name": "Apart",
		"cell": Vector2i(1, 2),
		"route": "main",
		"requires": ["3-7"],
		"source": "!cell-edge-v1\n\n[cells]\n.A##\n....\n#.B@\n#.##\n*.*#\n\n[horizontal_edges]\n....\n....\n....\n....\n\n[vertical_edges]\n...\n...\n...\n...\n...",
	},
	{
		"id": "3-9",
		"name": "Trident",
		"cell": Vector2i(2, 2),
		"route": "main",
		"requires": ["3-8"],
		"source": "!cell-edge-v1\n\n[cells]\n##C##\n.#.#.\n..A..\n.#@#B\n*.*.*\n\n[horizontal_edges]\n.....\n.....\n.....\n.....\n\n[vertical_edges]\n....\n....\n....\n....\n....",
	},
	{
		"id": "3-10",
		"name": "Corridor",
		"cell": Vector2i(3, 2),
		"route": "main",
		"requires": ["3-9"],
		"source": "!cell-edge-v1\n\n[cells]\n*..*.#D.\n+A.BC...\n###*.###\n\n[horizontal_edges]\n-.--....\n...-....\n\n[vertical_edges]\n.......\n.......\n.......",
	},
	{
		"id": "3-11",
		"name": "Phase",
		"cell": Vector2i(3, 1),
		"route": "main",
		"requires": ["3-10"],
		"source": "!cell-edge-v1\n\n[cells]\n#*c#\n##..\n*@A.\n..B.\n\n[horizontal_edges]\n....\n....\n....\n\n[vertical_edges]\n...\n...\n...\n...",
	},
]


const AREAS := {
	1: {
		"size": Vector2i(4, 3),
		"start_cell": Vector2i(0, 0),
		"exit_requirement": "1-10",
		"previous_area": 0,
		"next_area": 2,
		"levels": AREA_01_LEVELS,
	},
	2: {
		"size": Vector2i(4, 3),
		"start_cell": Vector2i(0, 0),
		"exit_requirement": "2-11",
		"previous_area": 1,
		"next_area": 3,
		"levels": AREA_02_LEVELS,
	},
	3: {
		"size": Vector2i(4, 3),
		"start_cell": Vector2i(0, 0),
		"exit_requirement": "3-11",
		"previous_area": 2,
		"next_area": 0,
		"levels": AREA_03_LEVELS,
	},
}
